version: "3.6"

volumes:
  edgedb-data:

services:
  edgedb:
    image: edgedb/edgedb
    hostname: edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_TLS_CERT_MODE: generate_self_signed
      EDGEDB_SERVER_DATABASE: edgedb
      EDGEDB_SERVER_USER: edgedb
      EDGEDB_SERVER_PASSWORD: secret
      EDGEDB_SERVER_ADMIN_UI: enabled
    volumes:
      - ./edgedb/dbschema:/dbschema
      - edgedb-data:/var/lib/edgedb/data
    ports:
      - "5658:5656"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5656/server/status/ready"]
      interval: 1s
      timeout: 5s
      retries: 20
      start_period: 10s

  go-test:
    build:
      context: go-test
    restart: always
    environment:
      EDGEDB_DSN: 'edgedb://edgedb:secret@edgedb:5656/edgedb?tls_security=insecure'
    depends_on:
      edgedb:
        condition: service_healthy

  js-test:
    build:
      context: js-test
    restart: always
    environment:
      EDGEDB_DSN: 'edgedb://edgedb:secret@edgedb:5656/edgedb?tls_security=insecure'
    depends_on:
      edgedb:
        condition: service_healthy
